### ISSUE TITLE
How to use ? 

### ISSUE THREAD

**Issue by KarimelQ** [chengstark/SegMADe#1]
Hello , 

Could you give some hints on how / what script to run to use this annotator tool ? 

Thank's

**Comment by chengstark** [comment]
Sorry for the very late reply, the annotator tool setup would require you to configure your own local host. If you would like to host it on a server, you will need to set up gunicorn and nginx. The process is dependent on several factors, such as your server's os, network settings etc, so I'm not able to provide assistance on this. The tool's web code is available for your adaptation depending on your need.
